# fly.toml app configuration file generated for demux on 2023-12-11T06:07:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "demux"
primary_region = "iad"
kill_signal = "SIGTERM"
swap_size_mb = 3096

[build]

# [deploy]
#   release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "bold.video"
  PORT = "8080"

[[mounts]]
  source = "uploads"
  destination = "app/uploads"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
